kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: gitless-gitops
runtimeConfig:
  "api/alpha": "false"
  "api/beta": "false"
featureGates:
  KubeletInUserNamespace: true
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."zot.oci.svc.cluster.local"]
      endpoint = ["http://10.96.13.125"]