apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  {{- include "agent.metadata" . | nindent 2 }}
    component: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      component: agent
      environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        component: agent
        environment: {{ .Values.environment }}
    spec:
      hostUsers: false
      serviceAccountName: {{ .Values.environment }}-{{ .Chart.Name }}-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: agent
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        image: "{{ .Values.registry_url }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        startupProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /status
            port: http
          initialDelaySeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 15Mi
            limits:
              cpu: 20m
              memory: 25Mi
---
apiVersion: v1
kind: Service
metadata:
  name: agent
  {{- include "agent.metadata" . | nindent 2 }}
    component: agent
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    component: agent
    environment: {{ .Values.environment }}