apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.environment }}-{{ .Chart.Name }}-sa
  {{- include "agent.metadata" . | nindent 2 }}
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name:  {{ .Chart.Name }}
  namespace: {{ .Values.environment }}
  labels:
  {{- include "agent.labels" . | nindent 4}}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  - serviceaccounts
  verbs:
  - create
  - delete
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.environment }}
  labels:
  {{- include "agent.labels" . | nindent 4}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name:  {{ .Chart.Name }}
subjects:
- kind: ServiceAccount
  name:  {{ .Values.environment }}-{{ .Chart.Name }}-sa
  namespace: dev-agent
---