FROM golang:alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY main.go .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

# Create minimal container with the scratch image
FROM scratch
ENV PORT 8080
EXPOSE $PORT
ENV RULES_FILE=/rules.yaml
VOLUME ["/rules.yaml"]
COPY --from=builder /app/app /app
ENTRYPOINT ["/app"]